export USE_LXC=1
export GITIAN_HOST_IP=10.0.3.2
export LXC_GUEST_IP=10.0.3.5

## see bugs https://github.com/devrandom/gitian-builder/issues/56 and https://bugzilla.mindrot.org/show_bug.cgi?id=1285
for ENV in $(env | grep ^LC | awk -F= '{ print $1 }'); do
        unset $ENV
done

export LANG=en_US.UTF-8
